
GottaGoFastHistoryDB = {
	["profileKeys"] = {
		["Evisca - Bleeding Hollow"] = "Default",
		["Praerend - Proudmoore"] = "Default",
		["Kaldorath - Proudmoore"] = "Default",
		["Gorog - Bleeding Hollow"] = "Default",
		["Amranar - Proudmoore"] = "Default",
		["Farahn - Proudmoore"] = "Default",
		["Fimwack - Proudmoore"] = "Default",
		["Mallusof - Tichondrius"] = "Default",
		["Gottagetlia - Aggramar"] = "Default",
		["Granjior - Proudmoore"] = "Default",
		["Zaliga - Bleeding Hollow"] = "Default",
		["Miriyal - Proudmoore"] = "Default",
		["Greybone - Proudmoore"] = "Default",
		["Morifa - Proudmoore"] = "Default",
		["Faerand - Proudmoore"] = "Default",
		["Rahran - Proudmoore"] = "Default",
	},
	["profiles"] = {
		["Default"] = {
			["History"] = {
				[1677] = {
					["objectives"] = {
						"Agronox", -- [1]
						"Thrashbite", -- [2]
						"Domatrax", -- [3]
						"Mephistroth", -- [4]
						"Enemy Forces", -- [5]
					},
					["zoneID"] = 1677,
					["name"] = "Cathedral of Eternal Night",
					["runs"] = {
						{
							["corrupt"] = false,
							["deaths"] = 32,
							["affixes"] = {
								[2] = {
									["name"] = "Skittish",
									["desc"] = "Enemies pay far less attention to threat generated by tanks.",
								},
								[7] = {
									["name"] = "Bolstering",
									["desc"] = "When any non-boss enemy dies, its death cry empowers nearby allies, increasing their maximum health and damage by 20%.",
								},
								[10] = {
									["name"] = "Fortified",
									["desc"] = "Non-boss enemies have 20% more health and inflict up to 30% increased damage.",
								},
							},
							["active"] = false,
							["endTime"] = 15603.617,
							["timeStamp"] = {
								["day"] = 17,
								["month"] = 5,
								["hours"] = 23,
								["year"] = 2017,
								["mins"] = 54,
							},
							["level"] = 13,
							["startTime"] = 13492.732,
							["objectiveTimes"] = {
								"11:14.997", -- [1]
								"24:02.184", -- [2]
								"35:09.486", -- [3]
								"37:50.491", -- [4]
								"35:38.921", -- [5]
							},
							["players"] = {
								{
									["class"] = "Monk",
									["name"] = "Coaxed",
									["role"] = "DAMAGER",
								}, -- [1]
								{
									["class"] = "Monk",
									["name"] = "Ileiaris",
									["role"] = "TANK",
								}, -- [2]
								{
									["class"] = "Paladin",
									["name"] = "Blakeyboy",
									["role"] = "DAMAGER",
								}, -- [3]
								{
									["class"] = "Paladin",
									["name"] = "Eärendìl",
									["role"] = "DAMAGER",
								}, -- [4]
								{
									["class"] = "Priest",
									["name"] = "Mallusof",
									["role"] = "HEALER",
								}, -- [5]
							},
						}, -- [1]
					},
				},
				[1501] = {
					["objectives"] = {
						"Amalgam of Souls", -- [1]
						"Illysanna Ravencrest", -- [2]
						"Smashspite the Hateful", -- [3]
						"Lord Kur'talos Ravencrest", -- [4]
						"Enemy Forces", -- [5]
					},
					["zoneID"] = 1501,
					["name"] = "Black Rook Hold",
					["runs"] = {
						{
							["corrupt"] = false,
							["deaths"] = 7,
							["affixes"] = {
								[11] = {
									["name"] = "Bursting",
									["desc"] = "When slain, non-boss enemies explode, causing all players to suffer 10% of their max health in damage over 4 sec. This effect stacks.",
								},
								[2] = {
									["name"] = "Skittish",
									["desc"] = "Enemies pay far less attention to threat generated by tanks.",
								},
								[9] = {
									["name"] = "Tyrannical",
									["desc"] = "Boss enemies have 40% more health and inflict up to 15% increased damage.",
								},
							},
							["active"] = false,
							["endTime"] = 12292.358,
							["timeStamp"] = {
								["day"] = 30,
								["month"] = 4,
								["hours"] = 14,
								["year"] = 2017,
								["mins"] = 23,
							},
							["level"] = 12,
							["startTime"] = 10963.762,
							["objectiveTimes"] = {
								"02:13.571", -- [1]
								"10:50.927", -- [2]
								"18:22.987", -- [3]
								"22:43.152", -- [4]
								"20:15.676", -- [5]
							},
							["players"] = {
								{
									["class"] = "Death Knight",
									["name"] = "Lacosanostra (*)",
									["role"] = "TANK",
								}, -- [1]
								{
									["class"] = "Warrior",
									["name"] = "Archaous (*)",
									["role"] = "DAMAGER",
								}, -- [2]
								{
									["class"] = "Demon Hunter",
									["name"] = "Divinechaos (*)",
									["role"] = "DAMAGER",
								}, -- [3]
								{
									["class"] = "Rogue",
									["name"] = "Kynthaara (*)",
									["role"] = "DAMAGER",
								}, -- [4]
								{
									["class"] = "Priest",
									["name"] = "Mallusof",
									["role"] = "HEALER",
								}, -- [5]
							},
						}, -- [1]
						{
							["corrupt"] = false,
							["deaths"] = 20,
							["affixes"] = {
								[11] = {
									["name"] = "Bursting",
									["desc"] = "When slain, non-boss enemies explode, causing all players to suffer 10% of their max health in damage over 4 sec. This effect stacks.",
								},
								[2] = {
									["name"] = "Skittish",
									["desc"] = "Enemies pay far less attention to threat generated by tanks.",
								},
								[9] = {
									["name"] = "Tyrannical",
									["desc"] = "Boss enemies have 40% more health and inflict up to 15% increased damage.",
								},
							},
							["active"] = false,
							["endTime"] = 14735.689,
							["timeStamp"] = {
								["day"] = 30,
								["month"] = 4,
								["hours"] = 15,
								["year"] = 2017,
								["mins"] = 3,
							},
							["level"] = 11,
							["startTime"] = 12694.76,
							["objectiveTimes"] = {
								"05:35.038", -- [1]
								"15:39.886", -- [2]
								"29:04.169", -- [3]
								"35:40.450", -- [4]
								"32:04.754", -- [5]
							},
							["players"] = {
								{
									["class"] = "Paladin",
									["name"] = "Gooseboy (*)",
									["role"] = "TANK",
								}, -- [1]
								{
									["class"] = "Rogue",
									["name"] = "Knavish (*)",
									["role"] = "DAMAGER",
								}, -- [2]
								{
									["class"] = "Demon Hunter",
									["name"] = "Forcemajeure (*)",
									["role"] = "DAMAGER",
								}, -- [3]
								{
									["class"] = "Warlock",
									["name"] = "Alpacalunch (*)",
									["role"] = "DAMAGER",
								}, -- [4]
								{
									["class"] = "Priest",
									["name"] = "Mallusof",
									["role"] = "HEALER",
								}, -- [5]
							},
						}, -- [2]
						{
							["corrupt"] = false,
							["deaths"] = 13,
							["affixes"] = {
								[14] = {
									["name"] = "Quaking",
									["desc"] = "Periodically, all players emit a shockwave, inflicting damage and interrupting nearby allies.",
								},
								[10] = {
									["name"] = "Fortified",
									["desc"] = "Non-boss enemies have 20% more health and inflict up to 30% increased damage.",
								},
								[5] = {
									["name"] = "Teeming",
									["desc"] = "Additional non-boss enemies are present throughout the dungeon.",
								},
							},
							["active"] = false,
							["endTime"] = 6965.465,
							["timeStamp"] = {
								["day"] = 2,
								["month"] = 5,
								["hours"] = 21,
								["year"] = 2017,
								["mins"] = 18,
							},
							["level"] = 11,
							["startTime"] = 5579.52,
							["objectiveTimes"] = {
								"01:52.826", -- [1]
								"10:01.117", -- [2]
								"18:50.151", -- [3]
								"24:10.434", -- [4]
								"22:39.823", -- [5]
							},
							["players"] = {
								{
									["class"] = "Paladin",
									["name"] = "Kalithumos",
									["role"] = "TANK",
								}, -- [1]
								{
									["class"] = "Death Knight",
									["name"] = "Kaedwyn",
									["role"] = "DAMAGER",
								}, -- [2]
								{
									["class"] = "Mage",
									["name"] = "Mediocreman",
									["role"] = "DAMAGER",
								}, -- [3]
								{
									["class"] = "Paladin",
									["name"] = "Eärendìl",
									["role"] = "DAMAGER",
								}, -- [4]
								{
									["class"] = "Priest",
									["name"] = "Mallusof",
									["role"] = "HEALER",
								}, -- [5]
							},
						}, -- [3]
						{
							["corrupt"] = false,
							["deaths"] = 32,
							["affixes"] = {
								[6] = {
									["name"] = "Raging",
									["desc"] = "Non-boss enemies enrage at 30% health remaining, dealing 100% increased damage until defeated.",
								},
								[4] = {
									["name"] = "Necrotic",
									["desc"] = "All enemies' melee attacks apply a stacking blight that inflicts damage over time and reduces healing received.",
								},
								[9] = {
									["name"] = "Tyrannical",
									["desc"] = "Boss enemies have 40% more health and inflict up to 15% increased damage.",
								},
							},
							["active"] = false,
							["endTime"] = 13648.755,
							["timeStamp"] = {
								["day"] = 11,
								["month"] = 5,
								["hours"] = 22,
								["year"] = 2017,
								["mins"] = 47,
							},
							["level"] = 17,
							["startTime"] = 11277.41,
							["objectiveTimes"] = {
								"03:56.795", -- [1]
								"25:06.999", -- [2]
								"35:16.379", -- [3]
								"42:10.810", -- [4]
								"38:34.819", -- [5]
							},
							["players"] = {
								{
									["class"] = "Paladin",
									["name"] = "Kalithumos",
									["role"] = "TANK",
								}, -- [1]
								{
									["class"] = "Mage",
									["name"] = "Kaligon",
									["role"] = "DAMAGER",
								}, -- [2]
								{
									["class"] = "Warlock",
									["name"] = "Arkator",
									["role"] = "DAMAGER",
								}, -- [3]
								{
									["class"] = "Mage",
									["name"] = "Slimane",
									["role"] = "DAMAGER",
								}, -- [4]
								{
									["class"] = "Priest",
									["name"] = "Mallusof",
									["role"] = "HEALER",
								}, -- [5]
							},
						}, -- [4]
						{
							["corrupt"] = false,
							["deaths"] = 10,
							["affixes"] = {
								[6] = {
									["name"] = "Raging",
									["desc"] = "Non-boss enemies enrage at 30% health remaining, dealing 100% increased damage until defeated.",
								},
								[4] = {
									["name"] = "Necrotic",
									["desc"] = "All enemies' melee attacks apply a stacking blight that inflicts damage over time and reduces healing received.",
								},
								[9] = {
									["name"] = "Tyrannical",
									["desc"] = "Boss enemies have 40% more health and inflict up to 15% increased damage.",
								},
							},
							["active"] = false,
							["endTime"] = 40903.56,
							["timeStamp"] = {
								["day"] = 13,
								["month"] = 5,
								["hours"] = 21,
								["year"] = 2017,
								["mins"] = 26,
							},
							["startTime"] = 39529.861,
							["level"] = 11,
							["objectiveTimes"] = {
								"02:59.072", -- [1]
								"10:33.728", -- [2]
								"19:18.422", -- [3]
								"23:43.247", -- [4]
								"21:17.453", -- [5]
							},
							["players"] = {
								{
									["class"] = "Mage",
									["name"] = "Geturownfood (*)",
									["role"] = "DAMAGER",
								}, -- [1]
								{
									["class"] = "Paladin",
									["name"] = "Lightmaker (*)",
									["role"] = "DAMAGER",
								}, -- [2]
								{
									["class"] = "Mage",
									["name"] = "Nukebom (*)",
									["role"] = "DAMAGER",
								}, -- [3]
								{
									["class"] = "Death Knight",
									["name"] = "Teäch (*)",
									["role"] = "TANK",
								}, -- [4]
								{
									["class"] = "Priest",
									["name"] = "Mallusof",
									["role"] = "HEALER",
								}, -- [5]
							},
						}, -- [5]
						{
							["corrupt"] = false,
							["deaths"] = 2,
							["affixes"] = {
							},
							["active"] = false,
							["endTime"] = 2126.572,
							["timeStamp"] = {
								["day"] = 20,
								["month"] = 5,
								["hours"] = 17,
								["year"] = 2017,
								["mins"] = 4,
							},
							["level"] = 2,
							["startTime"] = 1282.314,
							["objectiveTimes"] = {
								"02:39.748", -- [1]
								"07:40.971", -- [2]
								"11:27.304", -- [3]
								"14:13.817", -- [4]
								"12:31.451", -- [5]
							},
							["players"] = {
								{
									["class"] = "Warlock",
									["name"] = "Smokinggas (*)",
									["role"] = "DAMAGER",
								}, -- [1]
								{
									["class"] = "Demon Hunter",
									["name"] = "Mecc (*)",
									["role"] = "TANK",
								}, -- [2]
								{
									["class"] = "Hunter",
									["name"] = "Ozai (*)",
									["role"] = "DAMAGER",
								}, -- [3]
								{
									["class"] = "Rogue",
									["name"] = "Getstàbbed (*)",
									["role"] = "DAMAGER",
								}, -- [4]
								{
									["class"] = "Priest",
									["name"] = "Mallusof",
									["role"] = "DAMAGER",
								}, -- [5]
							},
						}, -- [6]
						{
							["corrupt"] = false,
							["deaths"] = 13,
							["affixes"] = {
								[5] = {
									["name"] = "Teeming",
									["desc"] = "Additional non-boss enemies are present throughout the dungeon.",
								},
								[4] = {
									["name"] = "Necrotic",
									["desc"] = "All enemies' melee attacks apply a stacking blight that inflicts damage over time and reduces healing received.",
								},
							},
							["active"] = false,
							["endTime"] = 3495.179,
							["timeStamp"] = {
								["day"] = 28,
								["month"] = 5,
								["hours"] = 11,
								["year"] = 2017,
								["mins"] = 59,
							},
							["level"] = 7,
							["startTime"] = 2089.354,
							["objectiveTimes"] = {
								"04:16.102", -- [1]
								"10:33.934", -- [2]
								"20:30.196", -- [3]
								"24:30.231", -- [4]
								"22:32.523", -- [5]
							},
							["players"] = {
								{
									["class"] = "Death Knight",
									["name"] = "Mylilgnomey (*)",
									["role"] = "TANK",
								}, -- [1]
								{
									["class"] = "Rogue",
									["name"] = "Wolfsneakers (*)",
									["role"] = "DAMAGER",
								}, -- [2]
								{
									["class"] = "Paladin",
									["name"] = "Mesmor (*)",
									["role"] = "DAMAGER",
								}, -- [3]
								{
									["class"] = "Monk",
									["name"] = "Oppaii (*)",
									["role"] = "DAMAGER",
								}, -- [4]
								{
									["class"] = "Priest",
									["name"] = "Mallusof",
									["role"] = "HEALER",
								}, -- [5]
							},
						}, -- [7]
						{
							["corrupt"] = false,
							["deaths"] = 13,
							["affixes"] = {
								[5] = {
									["name"] = "Teeming",
									["desc"] = "Additional non-boss enemies are present throughout the dungeon.",
								},
								[4] = {
									["name"] = "Necrotic",
									["desc"] = "All enemies' melee attacks apply a stacking blight that inflicts damage over time and reduces healing received.",
								},
								[9] = {
									["name"] = "Tyrannical",
									["desc"] = "Boss enemies have 40% more health and inflict up to 15% increased damage.",
								},
							},
							["active"] = false,
							["endTime"] = 31272.092,
							["timeStamp"] = {
								["day"] = 29,
								["month"] = 5,
								["hours"] = 1,
								["year"] = 2017,
								["mins"] = 34,
							},
							["level"] = 10,
							["startTime"] = 29940.675,
							["objectiveTimes"] = {
								"02:04.374", -- [1]
								"10:37.361", -- [2]
								"19:11.315", -- [3]
								"23:15.891", -- [4]
								"21:01.229", -- [5]
							},
							["players"] = {
								{
									["class"] = "Warrior",
									["name"] = "Jinnk (*)",
									["role"] = "TANK",
								}, -- [1]
								{
									["class"] = "Death Knight",
									["name"] = "Gravyroll (*)",
									["role"] = "DAMAGER",
								}, -- [2]
								{
									["class"] = "Death Knight",
									["name"] = "Deathstair (*)",
									["role"] = "DAMAGER",
								}, -- [3]
								{
									["class"] = "Mage",
									["name"] = "Ìkaris (*)",
									["role"] = "DAMAGER",
								}, -- [4]
								{
									["class"] = "Priest",
									["name"] = "Mallusof",
									["role"] = "HEALER",
								}, -- [5]
							},
						}, -- [8]
						{
							["corrupt"] = false,
							["deaths"] = 7,
							["affixes"] = {
								[5] = {
									["name"] = "Teeming",
									["desc"] = "Additional non-boss enemies are present throughout the dungeon.",
								},
								[4] = {
									["name"] = "Necrotic",
									["desc"] = "All enemies' melee attacks apply a stacking blight that inflicts damage over time and reduces healing received.",
								},
								[9] = {
									["name"] = "Tyrannical",
									["desc"] = "Boss enemies have 40% more health and inflict up to 15% increased damage.",
								},
							},
							["active"] = false,
							["endTime"] = 44559.876,
							["timeStamp"] = {
								["day"] = 29,
								["month"] = 5,
								["hours"] = 23,
								["mins"] = 13,
								["year"] = 2017,
							},
							["players"] = {
								{
									["class"] = "Hunter",
									["name"] = "Fuzzybutt (*)",
									["role"] = "DAMAGER",
								}, -- [1]
								{
									["class"] = "Monk",
									["name"] = "Tylai (*)",
									["role"] = "TANK",
								}, -- [2]
								{
									["class"] = "Monk",
									["name"] = "Slippyfists (*)",
									["role"] = "DAMAGER",
								}, -- [3]
								{
									["class"] = "Shaman",
									["name"] = "Ketang (*)",
									["role"] = "DAMAGER",
								}, -- [4]
								{
									["class"] = "Priest",
									["name"] = "Mallusof",
									["role"] = "HEALER",
								}, -- [5]
							},
							["level"] = 13,
							["objectiveTimes"] = {
								"05:41.294", -- [1]
								"19:23.417", -- [2]
								"28:34.475", -- [3]
								"37:01.102", -- [4]
								"31:54.934", -- [5]
							},
							["startTime"] = 42373.241,
						}, -- [9]
					},
				},
				[1516] = {
					["objectives"] = {
						"Ivanyr", -- [1]
						"Corstilax", -- [2]
						"General Xakal", -- [3]
						"Nal'tira", -- [4]
						"Advisor Vandros", -- [5]
						"Enemy Forces", -- [6]
					},
					["zoneID"] = 1516,
					["name"] = "The Arcway",
					["runs"] = {
						{
							["corrupt"] = false,
							["deaths"] = 16,
							["affixes"] = {
								[6] = {
									["name"] = "Raging",
									["desc"] = "Non-boss enemies enrage at 30% health remaining, dealing 100% increased damage until defeated.",
								},
								[4] = {
									["name"] = "Necrotic",
									["desc"] = "All enemies' melee attacks apply a stacking blight that inflicts damage over time and reduces healing received.",
								},
								[9] = {
									["name"] = "Tyrannical",
									["desc"] = "Boss enemies have 40% more health and inflict up to 15% increased damage.",
								},
							},
							["active"] = false,
							["endTime"] = 17302.358,
							["timeStamp"] = {
								["day"] = 11,
								["month"] = 5,
								["hours"] = 23,
								["year"] = 2017,
								["mins"] = 48,
							},
							["level"] = 15,
							["startTime"] = 15691.333,
							["objectiveTimes"] = {
								"23:11.871", -- [1]
								"17:53.280", -- [2]
								"06:18.313", -- [3]
								"12:34.405", -- [4]
								"28:10.484", -- [5]
								"25:25.913", -- [6]
							},
							["players"] = {
								{
									["class"] = "Paladin",
									["name"] = "Kalithumos",
									["role"] = "TANK",
								}, -- [1]
								{
									["class"] = "Mage",
									["name"] = "Kaligon",
									["role"] = "DAMAGER",
								}, -- [2]
								{
									["class"] = "Warlock",
									["name"] = "Arkator",
									["role"] = "DAMAGER",
								}, -- [3]
								{
									["class"] = "Death Knight",
									["name"] = "Kaedwyn",
									["role"] = "DAMAGER",
								}, -- [4]
								{
									["class"] = "Priest",
									["name"] = "Mallusof",
									["role"] = "HEALER",
								}, -- [5]
							},
						}, -- [1]
						{
							["corrupt"] = false,
							["deaths"] = 22,
							["affixes"] = {
								[2] = {
									["name"] = "Skittish",
									["desc"] = "Enemies pay far less attention to threat generated by tanks.",
								},
								[7] = {
									["name"] = "Bolstering",
									["desc"] = "When any non-boss enemy dies, its death cry empowers nearby allies, increasing their maximum health and damage by 20%.",
								},
								[10] = {
									["name"] = "Fortified",
									["desc"] = "Non-boss enemies have 20% more health and inflict up to 30% increased damage.",
								},
							},
							["active"] = false,
							["endTime"] = 18270.869,
							["timeStamp"] = {
								["day"] = 20,
								["month"] = 5,
								["hours"] = 21,
								["mins"] = 33,
								["year"] = 2017,
							},
							["players"] = {
								{
									["class"] = "Monk",
									["name"] = "Ileiaris",
									["role"] = "TANK",
								}, -- [1]
								{
									["class"] = "Warlock",
									["name"] = "Arkator",
									["role"] = "DAMAGER",
								}, -- [2]
								{
									["class"] = "Paladin",
									["name"] = "Acekicker",
									["role"] = "DAMAGER",
								}, -- [3]
								{
									["class"] = "Death Knight",
									["name"] = "Zaelsynth",
									["role"] = "DAMAGER",
								}, -- [4]
								{
									["class"] = "Priest",
									["name"] = "Mallusof",
									["role"] = "HEALER",
								}, -- [5]
							},
							["startTime"] = 16294.016,
							["objectiveTimes"] = {
								"09:46.455", -- [1]
								"14:07.509", -- [2]
								"30:55.575", -- [3]
								"20:07.993", -- [4]
								"34:46.409", -- [5]
								"30:55.575", -- [6]
							},
							["level"] = 16,
						}, -- [2]
						{
							["corrupt"] = true,
							["deaths"] = 58,
							["affixes"] = {
								[2] = {
									["name"] = "Skittish",
									["desc"] = "Enemies pay far less attention to threat generated by tanks.",
								},
								[7] = {
									["name"] = "Bolstering",
									["desc"] = "When any non-boss enemy dies, its death cry empowers nearby allies, increasing their maximum health and damage by 20%.",
								},
								[10] = {
									["name"] = "Fortified",
									["desc"] = "Non-boss enemies have 20% more health and inflict up to 30% increased damage.",
								},
							},
							["active"] = false,
							["endTime"] = 20899.327,
							["timeStamp"] = {
								["day"] = 20,
								["month"] = 5,
								["hours"] = 22,
								["mins"] = 17,
								["year"] = 2017,
							},
							["players"] = {
								{
									["class"] = "Monk",
									["name"] = "Ileiaris",
									["role"] = "TANK",
								}, -- [1]
								{
									["class"] = "Warlock",
									["name"] = "Arkator",
									["role"] = "DAMAGER",
								}, -- [2]
								{
									["class"] = "Paladin",
									["name"] = "Acekicker",
									["role"] = "DAMAGER",
								}, -- [3]
								{
									["class"] = "Death Knight",
									["name"] = "Zaelsynth",
									["role"] = "DAMAGER",
								}, -- [4]
								{
									["class"] = "Priest",
									["name"] = "Mallusof",
									["role"] = "HEALER",
								}, -- [5]
							},
							["startTime"] = 18209.327,
							["objectiveTimes"] = {
								"39:40", -- [1]
								"33:16", -- [2]
								"19:45", -- [3]
								"26:22", -- [4]
								"44:50", -- [5]
								"41:49", -- [6]
							},
							["level"] = 18,
						}, -- [3]
						{
							["corrupt"] = false,
							["deaths"] = 2,
							["affixes"] = {
							},
							["active"] = false,
							["endTime"] = 13335.144,
							["timeStamp"] = {
								["day"] = 26,
								["month"] = 5,
								["hours"] = 22,
								["mins"] = 14,
								["year"] = 2017,
							},
							["players"] = {
								{
									["class"] = "Rogue",
									["name"] = "Jogebai (*)",
									["role"] = "DAMAGER",
								}, -- [1]
								{
									["class"] = "Demon Hunter",
									["name"] = "Miffle (*)",
									["role"] = "DAMAGER",
								}, -- [2]
								{
									["class"] = "Shaman",
									["name"] = "Shamalomin (*)",
									["role"] = "DAMAGER",
								}, -- [3]
								{
									["class"] = "Paladin",
									["name"] = "Hastiliarius (*)",
									["role"] = "TANK",
								}, -- [4]
								{
									["class"] = "Priest",
									["name"] = "Mallusof",
									["role"] = "HEALER",
								}, -- [5]
							},
							["startTime"] = 12300.514,
							["objectiveTimes"] = {
								"14:16.316", -- [1]
								"10:46.192", -- [2]
								"04:50.276", -- [3]
								"07:43.420", -- [4]
								"17:24.157", -- [5]
								"15:47.252", -- [6]
							},
							["level"] = 3,
						}, -- [4]
					},
				},
				[1571] = {
					["runs"] = {
						{
							["corrupt"] = false,
							["deaths"] = 4,
							["affixes"] = {
							},
							["active"] = false,
							["endTime"] = 18565.992,
							["timeStamp"] = {
								["day"] = 6,
								["month"] = 5,
								["hours"] = 17,
								["mins"] = 58,
								["year"] = 2017,
							},
							["players"] = {
								{
									["class"] = "Hunter",
									["name"] = "Falquion (*)",
									["role"] = "DAMAGER",
								}, -- [1]
								{
									["class"] = "Rogue",
									["name"] = "Noterus (*)",
									["role"] = "DAMAGER",
								}, -- [2]
								{
									["class"] = "Druid",
									["name"] = "Fleya (*)",
									["role"] = "HEALER",
								}, -- [3]
								{
									["class"] = "Paladin",
									["name"] = "Ramzi (*)",
									["role"] = "DAMAGER",
								}, -- [4]
								{
									["class"] = "Death Knight",
									["name"] = "Greybone",
									["role"] = "TANK",
								}, -- [5]
							},
							["level"] = 2,
							["objectiveTimes"] = {
								"06:51.013", -- [1]
								"16:28.623", -- [2]
								"21:10.514", -- [3]
								"16:28.623", -- [4]
							},
							["startTime"] = 17315.105,
						}, -- [1]
						{
							["corrupt"] = false,
							["deaths"] = 8,
							["affixes"] = {
								[6] = {
									["name"] = "Raging",
									["desc"] = "Non-boss enemies enrage at 30% health remaining, dealing 100% increased damage until defeated.",
								},
								[4] = {
									["name"] = "Necrotic",
									["desc"] = "All enemies' melee attacks apply a stacking blight that inflicts damage over time and reduces healing received.",
								},
								[9] = {
									["name"] = "Tyrannical",
									["desc"] = "Boss enemies have 40% more health and inflict up to 15% increased damage.",
								},
							},
							["active"] = false,
							["endTime"] = 15392.472,
							["timeStamp"] = {
								["day"] = 11,
								["month"] = 5,
								["hours"] = 23,
								["year"] = 2017,
								["mins"] = 16,
							},
							["level"] = 13,
							["startTime"] = 14303.36,
							["objectiveTimes"] = {
								"07:19.652", -- [1]
								"14:41.661", -- [2]
								"18:48.674", -- [3]
								"14:41.661", -- [4]
							},
							["players"] = {
								{
									["class"] = "Paladin",
									["name"] = "Kalithumos",
									["role"] = "TANK",
								}, -- [1]
								{
									["class"] = "Mage",
									["name"] = "Kaligon",
									["role"] = "DAMAGER",
								}, -- [2]
								{
									["class"] = "Warlock",
									["name"] = "Arkator",
									["role"] = "DAMAGER",
								}, -- [3]
								{
									["class"] = "Death Knight",
									["name"] = "Kaedwyn",
									["role"] = "DAMAGER",
								}, -- [4]
								{
									["class"] = "Priest",
									["name"] = "Mallusof",
									["role"] = "HEALER",
								}, -- [5]
							},
						}, -- [2]
						{
							["corrupt"] = false,
							["deaths"] = 18,
							["affixes"] = {
								[2] = {
									["name"] = "Skittish",
									["desc"] = "Enemies pay far less attention to threat generated by tanks.",
								},
								[7] = {
									["name"] = "Bolstering",
									["desc"] = "When any non-boss enemy dies, its death cry empowers nearby allies, increasing their maximum health and damage by 20%.",
								},
								[10] = {
									["name"] = "Fortified",
									["desc"] = "Non-boss enemies have 20% more health and inflict up to 30% increased damage.",
								},
							},
							["active"] = false,
							["endTime"] = 19570.117,
							["timeStamp"] = {
								["day"] = 18,
								["month"] = 5,
								["hours"] = 1,
								["year"] = 2017,
								["mins"] = 0,
							},
							["level"] = 17,
							["startTime"] = 17941.654,
							["objectiveTimes"] = {
								"07:47.969", -- [1]
								"22:37.766", -- [2]
								"28:37.920", -- [3]
								"22:37.766", -- [4]
							},
							["players"] = {
								{
									["class"] = "Monk",
									["name"] = "Coaxed",
									["role"] = "DAMAGER",
								}, -- [1]
								{
									["class"] = "Death Knight",
									["name"] = "Kaedwyn",
									["role"] = "TANK",
								}, -- [2]
								{
									["class"] = "Paladin",
									["name"] = "Blakeyboy",
									["role"] = "DAMAGER",
								}, -- [3]
								{
									["class"] = "Paladin",
									["name"] = "Eärendìl",
									["role"] = "DAMAGER",
								}, -- [4]
								{
									["class"] = "Priest",
									["name"] = "Mallusof",
									["role"] = "HEALER",
								}, -- [5]
							},
						}, -- [3]
						{
							["corrupt"] = false,
							["deaths"] = 1,
							["affixes"] = {
								[5] = {
									["name"] = "Teeming",
									["desc"] = "Additional non-boss enemies are present throughout the dungeon.",
								},
								[4] = {
									["name"] = "Necrotic",
									["desc"] = "All enemies' melee attacks apply a stacking blight that inflicts damage over time and reduces healing received.",
								},
								[9] = {
									["name"] = "Tyrannical",
									["desc"] = "Boss enemies have 40% more health and inflict up to 15% increased damage.",
								},
							},
							["active"] = false,
							["endTime"] = 21327.287,
							["timeStamp"] = {
								["day"] = 28,
								["month"] = 5,
								["hours"] = 22,
								["mins"] = 48,
								["year"] = 2017,
							},
							["players"] = {
								{
									["class"] = "Druid",
									["name"] = "Shiftháppeñs (*)",
									["role"] = "TANK",
								}, -- [1]
								{
									["class"] = "Shaman",
									["name"] = "Cousinavi (*)",
									["role"] = "DAMAGER",
								}, -- [2]
								{
									["class"] = "Demon Hunter",
									["name"] = "Ryses (*)",
									["role"] = "DAMAGER",
								}, -- [3]
								{
									["class"] = "Paladin",
									["name"] = "Ssquirtle (*)",
									["role"] = "DAMAGER",
								}, -- [4]
								{
									["class"] = "Priest",
									["name"] = "Mallusof",
									["role"] = "HEALER",
								}, -- [5]
							},
							["level"] = 12,
							["objectiveTimes"] = {
								"05:30.883", -- [1]
								"14:13.884", -- [2]
								"19:13.957", -- [3]
								"14:13.884", -- [4]
							},
							["startTime"] = 20177.772,
						}, -- [4]
					},
					["name"] = "Court of Stars",
					["zoneID"] = 1571,
					["objectives"] = {
						"Patrol Captain Gerdo", -- [1]
						"Talixae Flamewreath", -- [2]
						"Advisor Melandrus", -- [3]
						"Enemy Forces", -- [4]
					},
				},
				[1492] = {
					["objectives"] = {
						"Ymiron, the Fallen King", -- [1]
						"Harbaron", -- [2]
						"Helya", -- [3]
						"Enemy Forces", -- [4]
					},
					["zoneID"] = 1492,
					["name"] = "Maw of Souls",
					["runs"] = {
						{
							["corrupt"] = false,
							["deaths"] = 28,
							["affixes"] = {
								[14] = {
									["name"] = "Quaking",
									["desc"] = "Periodically, all players emit a shockwave, inflicting damage and interrupting nearby allies.",
								},
								[10] = {
									["name"] = "Fortified",
									["desc"] = "Non-boss enemies have 20% more health and inflict up to 30% increased damage.",
								},
								[5] = {
									["name"] = "Teeming",
									["desc"] = "Additional non-boss enemies are present throughout the dungeon.",
								},
							},
							["active"] = false,
							["endTime"] = 8907.722,
							["timeStamp"] = {
								["day"] = 2,
								["month"] = 5,
								["hours"] = 21,
								["year"] = 2017,
								["mins"] = 51,
							},
							["level"] = 13,
							["startTime"] = 7651.484,
							["objectiveTimes"] = {
								"03:02.506", -- [1]
								"08:35.812", -- [2]
								"23:15.617", -- [3]
								"17:29.652", -- [4]
							},
							["players"] = {
								{
									["class"] = "Paladin",
									["name"] = "Kalithumos",
									["role"] = "TANK",
								}, -- [1]
								{
									["class"] = "Death Knight",
									["name"] = "Kaedwyn",
									["role"] = "DAMAGER",
								}, -- [2]
								{
									["class"] = "Mage",
									["name"] = "Kaligon",
									["role"] = "DAMAGER",
								}, -- [3]
								{
									["class"] = "Paladin",
									["name"] = "Eärendìl",
									["role"] = "DAMAGER",
								}, -- [4]
								{
									["class"] = "Priest",
									["name"] = "Mallusof",
									["role"] = "HEALER",
								}, -- [5]
							},
						}, -- [1]
						{
							["corrupt"] = false,
							["deaths"] = 0,
							["affixes"] = {
								[5] = {
									["name"] = "Teeming",
									["desc"] = "Additional non-boss enemies are present throughout the dungeon.",
								},
							},
							["active"] = false,
							["endTime"] = 14544.233,
							["timeStamp"] = {
								["day"] = 26,
								["month"] = 5,
								["hours"] = 22,
								["mins"] = 32,
								["year"] = 2017,
							},
							["players"] = {
								{
									["class"] = "Rogue",
									["name"] = "Jogebai (*)",
									["role"] = "DAMAGER",
								}, -- [1]
								{
									["class"] = "Demon Hunter",
									["name"] = "Miffle (*)",
									["role"] = "DAMAGER",
								}, -- [2]
								{
									["class"] = "Shaman",
									["name"] = "Shamalomin (*)",
									["role"] = "DAMAGER",
								}, -- [3]
								{
									["class"] = "Paladin",
									["name"] = "Hastiliarius (*)",
									["role"] = "TANK",
								}, -- [4]
								{
									["class"] = "Priest",
									["name"] = "Mallusof",
									["role"] = "HEALER",
								}, -- [5]
							},
							["startTime"] = 13840.505,
							["objectiveTimes"] = {
								"01:43.910", -- [1]
								"05:36.566", -- [2]
								"11:43.290", -- [3]
								"08:57.310", -- [4]
							},
							["level"] = 6,
						}, -- [2]
						{
							["corrupt"] = false,
							["deaths"] = 11,
							["affixes"] = {
								[5] = {
									["name"] = "Teeming",
									["desc"] = "Additional non-boss enemies are present throughout the dungeon.",
								},
								[4] = {
									["name"] = "Necrotic",
									["desc"] = "All enemies' melee attacks apply a stacking blight that inflicts damage over time and reduces healing received.",
								},
							},
							["active"] = false,
							["endTime"] = 5249.73,
							["timeStamp"] = {
								["day"] = 28,
								["month"] = 5,
								["hours"] = 12,
								["year"] = 2017,
								["mins"] = 29,
							},
							["level"] = 9,
							["startTime"] = 4253.321,
							["objectiveTimes"] = {
								"03:50.682", -- [1]
								"08:34.773", -- [2]
								"17:31.136", -- [3]
								"13:48.750", -- [4]
							},
							["players"] = {
								{
									["class"] = "Death Knight",
									["name"] = "Mylilgnomey (*)",
									["role"] = "TANK",
								}, -- [1]
								{
									["class"] = "Rogue",
									["name"] = "Wolfsneakers (*)",
									["role"] = "DAMAGER",
								}, -- [2]
								{
									["class"] = "Shaman",
									["name"] = "Shockpow (*)",
									["role"] = "DAMAGER",
								}, -- [3]
								{
									["class"] = "Monk",
									["name"] = "Oppaii (*)",
									["role"] = "DAMAGER",
								}, -- [4]
								{
									["class"] = "Priest",
									["name"] = "Mallusof",
									["role"] = "HEALER",
								}, -- [5]
							},
						}, -- [3]
					},
				},
				[1466] = {
					["objectives"] = {
						"Archdruid Glaidalis", -- [1]
						"Oakheart", -- [2]
						"Dresaron", -- [3]
						"Shade of Xavius", -- [4]
						"Enemy Forces", -- [5]
					},
					["zoneID"] = 1466,
					["name"] = "Darkheart Thicket",
					["runs"] = {
						{
							["corrupt"] = false,
							["deaths"] = 0,
							["affixes"] = {
							},
							["active"] = false,
							["endTime"] = 5925.754,
							["timeStamp"] = {
								["day"] = 9,
								["month"] = 5,
								["hours"] = 20,
								["year"] = 2017,
								["mins"] = 32,
							},
							["startTime"] = 5127.132,
							["level"] = 2,
							["objectiveTimes"] = {
								"03:31.497", -- [1]
								"07:30.772", -- [2]
								"10:23.923", -- [3]
								"13:18.225", -- [4]
								"12:22.916", -- [5]
							},
							["players"] = {
								{
									["class"] = "Demon Hunter",
									["name"] = "Quèenofdmg (*)",
									["role"] = "DAMAGER",
								}, -- [1]
								{
									["class"] = "Rogue",
									["name"] = "Hôtâru (*)",
									["role"] = "DAMAGER",
								}, -- [2]
								{
									["class"] = "Death Knight",
									["name"] = "Altena (*)",
									["role"] = "DAMAGER",
								}, -- [3]
								{
									["class"] = "Monk",
									["name"] = "Yasot (*)",
									["role"] = "HEALER",
								}, -- [4]
								{
									["class"] = "Death Knight",
									["name"] = "Greybone",
									["role"] = "TANK",
								}, -- [5]
							},
						}, -- [1]
						{
							["corrupt"] = false,
							["deaths"] = 6,
							["affixes"] = {
								[6] = {
									["name"] = "Raging",
									["desc"] = "Non-boss enemies enrage at 30% health remaining, dealing 100% increased damage until defeated.",
								},
								[4] = {
									["name"] = "Necrotic",
									["desc"] = "All enemies' melee attacks apply a stacking blight that inflicts damage over time and reduces healing received.",
								},
								[9] = {
									["name"] = "Tyrannical",
									["desc"] = "Boss enemies have 40% more health and inflict up to 15% increased damage.",
								},
							},
							["active"] = false,
							["endTime"] = 8478.982,
							["timeStamp"] = {
								["day"] = 11,
								["month"] = 5,
								["hours"] = 21,
								["year"] = 2017,
								["mins"] = 21,
							},
							["level"] = 13,
							["startTime"] = 7494.462,
							["objectiveTimes"] = {
								"04:21.410", -- [1]
								"09:26.032", -- [2]
								"13:19.546", -- [3]
								"16:54.041", -- [4]
								"15:00.636", -- [5]
							},
							["players"] = {
								{
									["class"] = "Paladin",
									["name"] = "Kalithumos",
									["role"] = "TANK",
								}, -- [1]
								{
									["class"] = "Mage",
									["name"] = "Kaligon",
									["role"] = "DAMAGER",
								}, -- [2]
								{
									["class"] = "Warlock",
									["name"] = "Arkator",
									["role"] = "DAMAGER",
								}, -- [3]
								{
									["class"] = "Mage",
									["name"] = "Slimane",
									["role"] = "DAMAGER",
								}, -- [4]
								{
									["class"] = "Priest",
									["name"] = "Mallusof",
									["role"] = "HEALER",
								}, -- [5]
							},
						}, -- [2]
						{
							["corrupt"] = false,
							["deaths"] = 10,
							["affixes"] = {
								[2] = {
									["name"] = "Skittish",
									["desc"] = "Enemies pay far less attention to threat generated by tanks.",
								},
								[7] = {
									["name"] = "Bolstering",
									["desc"] = "When any non-boss enemy dies, its death cry empowers nearby allies, increasing their maximum health and damage by 20%.",
								},
								[10] = {
									["name"] = "Fortified",
									["desc"] = "Non-boss enemies have 20% more health and inflict up to 30% increased damage.",
								},
							},
							["active"] = false,
							["endTime"] = 13033.34,
							["timeStamp"] = {
								["day"] = 17,
								["month"] = 5,
								["hours"] = 23,
								["year"] = 2017,
								["mins"] = 11,
							},
							["level"] = 10,
							["startTime"] = 12036.767,
							["objectiveTimes"] = {
								"04:33.077", -- [1]
								"08:36.910", -- [2]
								"13:55.178", -- [3]
								"17:26.098", -- [4]
								"16:31.213", -- [5]
							},
							["players"] = {
								{
									["class"] = "Monk",
									["name"] = "Coaxed",
									["role"] = "DAMAGER",
								}, -- [1]
								{
									["class"] = "Monk",
									["name"] = "Ileiaris",
									["role"] = "TANK",
								}, -- [2]
								{
									["class"] = "Paladin",
									["name"] = "Blakeyboy",
									["role"] = "DAMAGER",
								}, -- [3]
								{
									["class"] = "Paladin",
									["name"] = "Eärendìl",
									["role"] = "DAMAGER",
								}, -- [4]
								{
									["class"] = "Priest",
									["name"] = "Mallusof",
									["role"] = "HEALER",
								}, -- [5]
							},
						}, -- [3]
					},
				},
				[1651] = {
					["objectives"] = {
						"The Curator", -- [1]
						"Mana Devourer defeated", -- [2]
						"Shade of Medivh defeated", -- [3]
						"Viz'aduum the Watcher defeated", -- [4]
						"Enemy Forces", -- [5]
					},
					["zoneID"] = 1651,
					["name"] = "Return to Karazhan: Upper",
					["runs"] = {
						{
							["corrupt"] = false,
							["deaths"] = 14,
							["affixes"] = {
								[6] = {
									["name"] = "Raging",
									["desc"] = "Non-boss enemies enrage at 30% health remaining, dealing 100% increased damage until defeated.",
								},
							},
							["active"] = false,
							["endTime"] = 7809.088,
							["timeStamp"] = {
								["day"] = 9,
								["month"] = 5,
								["hours"] = 21,
								["year"] = 2017,
								["mins"] = 4,
							},
							["startTime"] = 6573.118,
							["level"] = 5,
							["objectiveTimes"] = {
								"05:34.641", -- [1]
								"11:29.219", -- [2]
								"08:37.056", -- [3]
								"21:45.529", -- [4]
								"15:05.625", -- [5]
							},
							["players"] = {
								{
									["class"] = "Monk",
									["name"] = "Kotlin (*)",
									["role"] = "DAMAGER",
								}, -- [1]
								{
									["class"] = "Warrior",
									["name"] = "Drogues (*)",
									["role"] = "DAMAGER",
								}, -- [2]
								{
									["class"] = "Demon Hunter",
									["name"] = "Syleria (*)",
									["role"] = "DAMAGER",
								}, -- [3]
								{
									["class"] = "Monk",
									["name"] = "Yasot (*)",
									["role"] = "HEALER",
								}, -- [4]
								{
									["class"] = "Death Knight",
									["name"] = "Greybone",
									["role"] = "TANK",
								}, -- [5]
							},
						}, -- [1]
					},
				},
				[1456] = {
					["objectives"] = {
						"Warlord Parjesh", -- [1]
						"Lady Hatecoil", -- [2]
						"King Deepbeard", -- [3]
						"Serpentrix", -- [4]
						"Wrath of Azshara", -- [5]
						"Enemy Forces", -- [6]
					},
					["zoneID"] = 1456,
					["name"] = "Eye of Azshara",
					["runs"] = {
						{
							["corrupt"] = false,
							["deaths"] = 25,
							["affixes"] = {
								[6] = {
									["name"] = "Raging",
									["desc"] = "Non-boss enemies enrage at 30% health remaining, dealing 100% increased damage until defeated.",
								},
								[4] = {
									["name"] = "Necrotic",
									["desc"] = "All enemies' melee attacks apply a stacking blight that inflicts damage over time and reduces healing received.",
								},
								[9] = {
									["name"] = "Tyrannical",
									["desc"] = "Boss enemies have 40% more health and inflict up to 15% increased damage.",
								},
							},
							["active"] = false,
							["endTime"] = 10687.545,
							["timeStamp"] = {
								["day"] = 11,
								["month"] = 5,
								["hours"] = 21,
								["year"] = 2017,
								["mins"] = 58,
							},
							["level"] = 16,
							["startTime"] = 8892.435,
							["objectiveTimes"] = {
								"04:29.105", -- [1]
								"10:18.058", -- [2]
								"24:11.977", -- [3]
								"16:11.778", -- [4]
								"31:59.522", -- [5]
								"26:53.704", -- [6]
							},
							["players"] = {
								{
									["class"] = "Paladin",
									["name"] = "Kalithumos",
									["role"] = "TANK",
								}, -- [1]
								{
									["class"] = "Mage",
									["name"] = "Kaligon",
									["role"] = "DAMAGER",
								}, -- [2]
								{
									["class"] = "Warlock",
									["name"] = "Arkator",
									["role"] = "DAMAGER",
								}, -- [3]
								{
									["class"] = "Mage",
									["name"] = "Slimane",
									["role"] = "DAMAGER",
								}, -- [4]
								{
									["class"] = "Priest",
									["name"] = "Mallusof",
									["role"] = "HEALER",
								}, -- [5]
							},
						}, -- [1]
					},
				},
				[1493] = {
					["objectives"] = {
						"Tirathon Saltheril", -- [1]
						"Inquisitor Tormentorum", -- [2]
						"Ash'golm", -- [3]
						"Glazer", -- [4]
						"Cordana Felsong", -- [5]
						"Enemy Forces", -- [6]
					},
					["zoneID"] = 1493,
					["name"] = "Vault of the Wardens",
					["runs"] = {
						{
							["corrupt"] = false,
							["deaths"] = 1,
							["affixes"] = {
								[11] = {
									["name"] = "Bursting",
									["desc"] = "When slain, non-boss enemies explode, causing all players to suffer 10% of their max health in damage over 4 sec. This effect stacks.",
								},
								[2] = {
									["name"] = "Skittish",
									["desc"] = "Enemies pay far less attention to threat generated by tanks.",
								},
								[9] = {
									["name"] = "Tyrannical",
									["desc"] = "Boss enemies have 40% more health and inflict up to 15% increased damage.",
								},
							},
							["active"] = false,
							["endTime"] = 9787.892,
							["timeStamp"] = {
								["day"] = 30,
								["month"] = 4,
								["hours"] = 13,
								["year"] = 2017,
								["mins"] = 41,
							},
							["level"] = 10,
							["startTime"] = 8471.782,
							["objectiveTimes"] = {
								"05:48.099", -- [1]
								"09:53.779", -- [2]
								"15:01.624", -- [3]
								"12:44.634", -- [4]
								"22:00.609", -- [5]
								"19:07.143", -- [6]
							},
							["players"] = {
								{
									["class"] = "Priest",
									["name"] = "Cazioh (*)",
									["role"] = "DAMAGER",
								}, -- [1]
								{
									["class"] = "Hunter",
									["name"] = "Glockcoma (*)",
									["role"] = "DAMAGER",
								}, -- [2]
								{
									["class"] = "Warrior",
									["name"] = "Omaigodx (*)",
									["role"] = "TANK",
								}, -- [3]
								{
									["class"] = "Mage",
									["name"] = "Xsirgodobalx (*)",
									["role"] = "DAMAGER",
								}, -- [4]
								{
									["class"] = "Priest",
									["name"] = "Mallusof",
									["role"] = "HEALER",
								}, -- [5]
							},
						}, -- [1]
						{
							["corrupt"] = false,
							["deaths"] = 4,
							["affixes"] = {
								[2] = {
									["name"] = "Skittish",
									["desc"] = "Enemies pay far less attention to threat generated by tanks.",
								},
								[7] = {
									["name"] = "Bolstering",
									["desc"] = "When any non-boss enemy dies, its death cry empowers nearby allies, increasing their maximum health and damage by 20%.",
								},
								[10] = {
									["name"] = "Fortified",
									["desc"] = "Non-boss enemies have 20% more health and inflict up to 30% increased damage.",
								},
							},
							["active"] = false,
							["endTime"] = 15809.95,
							["timeStamp"] = {
								["day"] = 20,
								["month"] = 5,
								["hours"] = 20,
								["mins"] = 52,
								["year"] = 2017,
							},
							["players"] = {
								{
									["class"] = "Monk",
									["name"] = "Ileiaris",
									["role"] = "TANK",
								}, -- [1]
								{
									["class"] = "Warlock",
									["name"] = "Arkator",
									["role"] = "DAMAGER",
								}, -- [2]
								{
									["class"] = "Paladin",
									["name"] = "Acekicker",
									["role"] = "DAMAGER",
								}, -- [3]
								{
									["class"] = "Death Knight",
									["name"] = "Zaelsynth",
									["role"] = "DAMAGER",
								}, -- [4]
								{
									["class"] = "Priest",
									["name"] = "Mallusof",
									["role"] = "HEALER",
								}, -- [5]
							},
							["startTime"] = 14607.043,
							["objectiveTimes"] = {
								"05:48.997", -- [1]
								"09:25.325", -- [2]
								"11:47.648", -- [3]
								"13:39.445", -- [4]
								"20:22.348", -- [5]
								"17:56.184", -- [6]
							},
							["level"] = 14,
						}, -- [2]
						{
							["corrupt"] = false,
							["deaths"] = 0,
							["affixes"] = {
							},
							["active"] = false,
							["endTime"] = 8095.934,
							["timeStamp"] = {
								["day"] = 21,
								["month"] = 5,
								["hours"] = 23,
								["year"] = 2017,
								["mins"] = 33,
							},
							["level"] = 3,
							["startTime"] = 7081.749,
							["objectiveTimes"] = {
								"03:25.607", -- [1]
								"06:34.176", -- [2]
								"08:18.196", -- [3]
								"10:09.357", -- [4]
								"16:53.742", -- [5]
								"14:32.844", -- [6]
							},
							["players"] = {
								{
									["class"] = "Mage",
									["name"] = "Shayelyn",
									["role"] = "DAMAGER",
								}, -- [1]
								{
									["class"] = "Warlock",
									["name"] = "Suïte (*)",
									["role"] = "DAMAGER",
								}, -- [2]
								{
									["class"] = "Priest",
									["name"] = "Defrokked (*)",
									["role"] = "HEALER",
								}, -- [3]
								{
									["class"] = "Warlock",
									["name"] = "Ahazu",
									["role"] = "DAMAGER",
								}, -- [4]
								{
									["class"] = "Death Knight",
									["name"] = "Greybone",
									["role"] = "TANK",
								}, -- [5]
							},
						}, -- [3]
					},
				},
				[1477] = {
					["objectives"] = {
						"Hymdall", -- [1]
						"Hyrja", -- [2]
						"Fenryr", -- [3]
						"God-King Skovald", -- [4]
						"Odyn", -- [5]
						"Enemy Forces", -- [6]
					},
					["zoneID"] = 1477,
					["name"] = "Halls of Valor",
					["runs"] = {
						{
							["corrupt"] = false,
							["deaths"] = 7,
							["affixes"] = {
								[2] = {
									["name"] = "Skittish",
									["desc"] = "Enemies pay far less attention to threat generated by tanks.",
								},
								[7] = {
									["name"] = "Bolstering",
									["desc"] = "When any non-boss enemy dies, its death cry empowers nearby allies, increasing their maximum health and damage by 20%.",
								},
								[10] = {
									["name"] = "Fortified",
									["desc"] = "Non-boss enemies have 20% more health and inflict up to 30% increased damage.",
								},
							},
							["active"] = false,
							["endTime"] = 17555.643,
							["timeStamp"] = {
								["day"] = 18,
								["month"] = 5,
								["hours"] = 0,
								["year"] = 2017,
								["mins"] = 27,
							},
							["level"] = 14,
							["startTime"] = 15974.685,
							["objectiveTimes"] = {
								"02:48.602", -- [1]
								"10:13.223", -- [2]
								"17:54.243", -- [3]
								"24:57.725", -- [4]
								"26:55.498", -- [5]
								"24:57.725", -- [6]
							},
							["players"] = {
								{
									["class"] = "Monk",
									["name"] = "Coaxed",
									["role"] = "DAMAGER",
								}, -- [1]
								{
									["class"] = "Monk",
									["name"] = "Ileiaris",
									["role"] = "TANK",
								}, -- [2]
								{
									["class"] = "Paladin",
									["name"] = "Blakeyboy",
									["role"] = "DAMAGER",
								}, -- [3]
								{
									["class"] = "Paladin",
									["name"] = "Eärendìl",
									["role"] = "DAMAGER",
								}, -- [4]
								{
									["class"] = "Priest",
									["name"] = "Mallusof",
									["role"] = "HEALER",
								}, -- [5]
							},
						}, -- [1]
					},
				},
			},
		},
	},
}
