
GottaGoFastHistoryDB = {
	["profileKeys"] = {
		["Evisca - Bleeding Hollow"] = "Default",
		["Amranar - Proudmoore"] = "Default",
		["Kaldorath - Proudmoore"] = "Default",
		["Gorog - Bleeding Hollow"] = "Default",
		["Praerend - Proudmoore"] = "Default",
		["Farahn - Proudmoore"] = "Default",
		["Fimwack - Proudmoore"] = "Default",
		["Mallusof - Tichondrius"] = "Default",
		["Gottagetlia - Aggramar"] = "Default",
		["Granjior - Proudmoore"] = "Default",
		["Zaliga - Bleeding Hollow"] = "Default",
		["Miriyal - Proudmoore"] = "Default",
		["Greybone - Proudmoore"] = "Default",
		["Morifa - Proudmoore"] = "Default",
		["Faerand - Proudmoore"] = "Default",
		["Rahran - Proudmoore"] = "Default",
	},
	["profiles"] = {
		["Default"] = {
			["History"] = {
				[1492] = {
					["runs"] = {
						{
							["corrupt"] = false,
							["deaths"] = 28,
							["affixes"] = {
								[14] = {
									["name"] = "Quaking",
									["desc"] = "Periodically, all players emit a shockwave, inflicting damage and interrupting nearby allies.",
								},
								[10] = {
									["name"] = "Fortified",
									["desc"] = "Non-boss enemies have 20% more health and inflict up to 30% increased damage.",
								},
								[5] = {
									["name"] = "Teeming",
									["desc"] = "Additional non-boss enemies are present throughout the dungeon.",
								},
							},
							["active"] = false,
							["endTime"] = 8907.722,
							["timeStamp"] = {
								["day"] = 2,
								["month"] = 5,
								["hours"] = 21,
								["mins"] = 51,
								["year"] = 2017,
							},
							["players"] = {
								{
									["class"] = "Paladin",
									["name"] = "Kalithumos",
									["role"] = "TANK",
								}, -- [1]
								{
									["class"] = "Death Knight",
									["name"] = "Kaedwyn",
									["role"] = "DAMAGER",
								}, -- [2]
								{
									["class"] = "Mage",
									["name"] = "Kaligon",
									["role"] = "DAMAGER",
								}, -- [3]
								{
									["class"] = "Paladin",
									["name"] = "Eärendìl",
									["role"] = "DAMAGER",
								}, -- [4]
								{
									["class"] = "Priest",
									["name"] = "Mallusof",
									["role"] = "HEALER",
								}, -- [5]
							},
							["startTime"] = 7651.484,
							["objectiveTimes"] = {
								"03:02.506", -- [1]
								"08:35.812", -- [2]
								"23:15.617", -- [3]
								"17:29.652", -- [4]
							},
							["level"] = 13,
						}, -- [1]
					},
					["name"] = "Maw of Souls",
					["zoneID"] = 1492,
					["objectives"] = {
						"Ymiron, the Fallen King", -- [1]
						"Harbaron", -- [2]
						"Helya", -- [3]
						"Enemy Forces", -- [4]
					},
				},
				[1493] = {
					["runs"] = {
						{
							["corrupt"] = false,
							["deaths"] = 1,
							["affixes"] = {
								[11] = {
									["name"] = "Bursting",
									["desc"] = "When slain, non-boss enemies explode, causing all players to suffer 10% of their max health in damage over 4 sec. This effect stacks.",
								},
								[2] = {
									["name"] = "Skittish",
									["desc"] = "Enemies pay far less attention to threat generated by tanks.",
								},
								[9] = {
									["name"] = "Tyrannical",
									["desc"] = "Boss enemies have 40% more health and inflict up to 15% increased damage.",
								},
							},
							["active"] = false,
							["endTime"] = 9787.892,
							["timeStamp"] = {
								["day"] = 30,
								["month"] = 4,
								["hours"] = 13,
								["mins"] = 41,
								["year"] = 2017,
							},
							["players"] = {
								{
									["class"] = "Priest",
									["name"] = "Cazioh (*)",
									["role"] = "DAMAGER",
								}, -- [1]
								{
									["class"] = "Hunter",
									["name"] = "Glockcoma (*)",
									["role"] = "DAMAGER",
								}, -- [2]
								{
									["class"] = "Warrior",
									["name"] = "Omaigodx (*)",
									["role"] = "TANK",
								}, -- [3]
								{
									["class"] = "Mage",
									["name"] = "Xsirgodobalx (*)",
									["role"] = "DAMAGER",
								}, -- [4]
								{
									["class"] = "Priest",
									["name"] = "Mallusof",
									["role"] = "HEALER",
								}, -- [5]
							},
							["startTime"] = 8471.782,
							["objectiveTimes"] = {
								"05:48.099", -- [1]
								"09:53.779", -- [2]
								"15:01.624", -- [3]
								"12:44.634", -- [4]
								"22:00.609", -- [5]
								"19:07.143", -- [6]
							},
							["level"] = 10,
						}, -- [1]
					},
					["name"] = "Vault of the Wardens",
					["zoneID"] = 1493,
					["objectives"] = {
						"Tirathon Saltheril", -- [1]
						"Inquisitor Tormentorum", -- [2]
						"Ash'golm", -- [3]
						"Glazer", -- [4]
						"Cordana Felsong", -- [5]
						"Enemy Forces", -- [6]
					},
				},
				[1651] = {
					["runs"] = {
						{
							["corrupt"] = false,
							["deaths"] = 14,
							["affixes"] = {
								[6] = {
									["name"] = "Raging",
									["desc"] = "Non-boss enemies enrage at 30% health remaining, dealing 100% increased damage until defeated.",
								},
							},
							["active"] = false,
							["endTime"] = 7809.088,
							["timeStamp"] = {
								["day"] = 9,
								["month"] = 5,
								["hours"] = 21,
								["mins"] = 4,
								["year"] = 2017,
							},
							["players"] = {
								{
									["class"] = "Monk",
									["name"] = "Kotlin (*)",
									["role"] = "DAMAGER",
								}, -- [1]
								{
									["class"] = "Warrior",
									["name"] = "Drogues (*)",
									["role"] = "DAMAGER",
								}, -- [2]
								{
									["class"] = "Demon Hunter",
									["name"] = "Syleria (*)",
									["role"] = "DAMAGER",
								}, -- [3]
								{
									["class"] = "Monk",
									["name"] = "Yasot (*)",
									["role"] = "HEALER",
								}, -- [4]
								{
									["class"] = "Death Knight",
									["name"] = "Greybone",
									["role"] = "TANK",
								}, -- [5]
							},
							["level"] = 5,
							["objectiveTimes"] = {
								"05:34.641", -- [1]
								"11:29.219", -- [2]
								"08:37.056", -- [3]
								"21:45.529", -- [4]
								"15:05.625", -- [5]
							},
							["startTime"] = 6573.118,
						}, -- [1]
					},
					["name"] = "Return to Karazhan: Upper",
					["zoneID"] = 1651,
					["objectives"] = {
						"The Curator", -- [1]
						"Mana Devourer defeated", -- [2]
						"Shade of Medivh defeated", -- [3]
						"Viz'aduum the Watcher defeated", -- [4]
						"Enemy Forces", -- [5]
					},
				},
				[1571] = {
					["objectives"] = {
						"Patrol Captain Gerdo", -- [1]
						"Talixae Flamewreath", -- [2]
						"Advisor Melandrus", -- [3]
						"Enemy Forces", -- [4]
					},
					["zoneID"] = 1571,
					["name"] = "Court of Stars",
					["runs"] = {
						{
							["corrupt"] = false,
							["deaths"] = 4,
							["affixes"] = {
							},
							["active"] = false,
							["endTime"] = 18565.992,
							["timeStamp"] = {
								["day"] = 6,
								["month"] = 5,
								["hours"] = 17,
								["year"] = 2017,
								["mins"] = 58,
							},
							["level"] = 2,
							["startTime"] = 17315.105,
							["objectiveTimes"] = {
								"06:51.013", -- [1]
								"16:28.623", -- [2]
								"21:10.514", -- [3]
								"16:28.623", -- [4]
							},
							["players"] = {
								{
									["class"] = "Hunter",
									["name"] = "Falquion (*)",
									["role"] = "DAMAGER",
								}, -- [1]
								{
									["class"] = "Rogue",
									["name"] = "Noterus (*)",
									["role"] = "DAMAGER",
								}, -- [2]
								{
									["class"] = "Druid",
									["name"] = "Fleya (*)",
									["role"] = "HEALER",
								}, -- [3]
								{
									["class"] = "Paladin",
									["name"] = "Ramzi (*)",
									["role"] = "DAMAGER",
								}, -- [4]
								{
									["class"] = "Death Knight",
									["name"] = "Greybone",
									["role"] = "TANK",
								}, -- [5]
							},
						}, -- [1]
					},
				},
				[1466] = {
					["runs"] = {
						{
							["corrupt"] = false,
							["deaths"] = 0,
							["affixes"] = {
							},
							["active"] = false,
							["endTime"] = 5925.754,
							["timeStamp"] = {
								["day"] = 9,
								["month"] = 5,
								["hours"] = 20,
								["mins"] = 32,
								["year"] = 2017,
							},
							["players"] = {
								{
									["class"] = "Demon Hunter",
									["name"] = "Quèenofdmg (*)",
									["role"] = "DAMAGER",
								}, -- [1]
								{
									["class"] = "Rogue",
									["name"] = "Hôtâru (*)",
									["role"] = "DAMAGER",
								}, -- [2]
								{
									["class"] = "Death Knight",
									["name"] = "Altena (*)",
									["role"] = "DAMAGER",
								}, -- [3]
								{
									["class"] = "Monk",
									["name"] = "Yasot (*)",
									["role"] = "HEALER",
								}, -- [4]
								{
									["class"] = "Death Knight",
									["name"] = "Greybone",
									["role"] = "TANK",
								}, -- [5]
							},
							["level"] = 2,
							["objectiveTimes"] = {
								"03:31.497", -- [1]
								"07:30.772", -- [2]
								"10:23.923", -- [3]
								"13:18.225", -- [4]
								"12:22.916", -- [5]
							},
							["startTime"] = 5127.132,
						}, -- [1]
					},
					["name"] = "Darkheart Thicket",
					["zoneID"] = 1466,
					["objectives"] = {
						"Archdruid Glaidalis", -- [1]
						"Oakheart", -- [2]
						"Dresaron", -- [3]
						"Shade of Xavius", -- [4]
						"Enemy Forces", -- [5]
					},
				},
				[1501] = {
					["runs"] = {
						{
							["corrupt"] = false,
							["deaths"] = 7,
							["affixes"] = {
								[11] = {
									["name"] = "Bursting",
									["desc"] = "When slain, non-boss enemies explode, causing all players to suffer 10% of their max health in damage over 4 sec. This effect stacks.",
								},
								[2] = {
									["name"] = "Skittish",
									["desc"] = "Enemies pay far less attention to threat generated by tanks.",
								},
								[9] = {
									["name"] = "Tyrannical",
									["desc"] = "Boss enemies have 40% more health and inflict up to 15% increased damage.",
								},
							},
							["active"] = false,
							["endTime"] = 12292.358,
							["timeStamp"] = {
								["day"] = 30,
								["month"] = 4,
								["hours"] = 14,
								["mins"] = 23,
								["year"] = 2017,
							},
							["players"] = {
								{
									["class"] = "Death Knight",
									["name"] = "Lacosanostra (*)",
									["role"] = "TANK",
								}, -- [1]
								{
									["class"] = "Warrior",
									["name"] = "Archaous (*)",
									["role"] = "DAMAGER",
								}, -- [2]
								{
									["class"] = "Demon Hunter",
									["name"] = "Divinechaos (*)",
									["role"] = "DAMAGER",
								}, -- [3]
								{
									["class"] = "Rogue",
									["name"] = "Kynthaara (*)",
									["role"] = "DAMAGER",
								}, -- [4]
								{
									["class"] = "Priest",
									["name"] = "Mallusof",
									["role"] = "HEALER",
								}, -- [5]
							},
							["startTime"] = 10963.762,
							["objectiveTimes"] = {
								"02:13.571", -- [1]
								"10:50.927", -- [2]
								"18:22.987", -- [3]
								"22:43.152", -- [4]
								"20:15.676", -- [5]
							},
							["level"] = 12,
						}, -- [1]
						{
							["corrupt"] = false,
							["deaths"] = 20,
							["affixes"] = {
								[11] = {
									["name"] = "Bursting",
									["desc"] = "When slain, non-boss enemies explode, causing all players to suffer 10% of their max health in damage over 4 sec. This effect stacks.",
								},
								[2] = {
									["name"] = "Skittish",
									["desc"] = "Enemies pay far less attention to threat generated by tanks.",
								},
								[9] = {
									["name"] = "Tyrannical",
									["desc"] = "Boss enemies have 40% more health and inflict up to 15% increased damage.",
								},
							},
							["active"] = false,
							["endTime"] = 14735.689,
							["timeStamp"] = {
								["day"] = 30,
								["month"] = 4,
								["hours"] = 15,
								["mins"] = 3,
								["year"] = 2017,
							},
							["players"] = {
								{
									["class"] = "Paladin",
									["name"] = "Gooseboy (*)",
									["role"] = "TANK",
								}, -- [1]
								{
									["class"] = "Rogue",
									["name"] = "Knavish (*)",
									["role"] = "DAMAGER",
								}, -- [2]
								{
									["class"] = "Demon Hunter",
									["name"] = "Forcemajeure (*)",
									["role"] = "DAMAGER",
								}, -- [3]
								{
									["class"] = "Warlock",
									["name"] = "Alpacalunch (*)",
									["role"] = "DAMAGER",
								}, -- [4]
								{
									["class"] = "Priest",
									["name"] = "Mallusof",
									["role"] = "HEALER",
								}, -- [5]
							},
							["startTime"] = 12694.76,
							["objectiveTimes"] = {
								"05:35.038", -- [1]
								"15:39.886", -- [2]
								"29:04.169", -- [3]
								"35:40.450", -- [4]
								"32:04.754", -- [5]
							},
							["level"] = 11,
						}, -- [2]
						{
							["corrupt"] = false,
							["deaths"] = 13,
							["affixes"] = {
								[14] = {
									["name"] = "Quaking",
									["desc"] = "Periodically, all players emit a shockwave, inflicting damage and interrupting nearby allies.",
								},
								[10] = {
									["name"] = "Fortified",
									["desc"] = "Non-boss enemies have 20% more health and inflict up to 30% increased damage.",
								},
								[5] = {
									["name"] = "Teeming",
									["desc"] = "Additional non-boss enemies are present throughout the dungeon.",
								},
							},
							["active"] = false,
							["endTime"] = 6965.465,
							["timeStamp"] = {
								["day"] = 2,
								["month"] = 5,
								["hours"] = 21,
								["mins"] = 18,
								["year"] = 2017,
							},
							["players"] = {
								{
									["class"] = "Paladin",
									["name"] = "Kalithumos",
									["role"] = "TANK",
								}, -- [1]
								{
									["class"] = "Death Knight",
									["name"] = "Kaedwyn",
									["role"] = "DAMAGER",
								}, -- [2]
								{
									["class"] = "Mage",
									["name"] = "Mediocreman",
									["role"] = "DAMAGER",
								}, -- [3]
								{
									["class"] = "Paladin",
									["name"] = "Eärendìl",
									["role"] = "DAMAGER",
								}, -- [4]
								{
									["class"] = "Priest",
									["name"] = "Mallusof",
									["role"] = "HEALER",
								}, -- [5]
							},
							["startTime"] = 5579.52,
							["objectiveTimes"] = {
								"01:52.826", -- [1]
								"10:01.117", -- [2]
								"18:50.151", -- [3]
								"24:10.434", -- [4]
								"22:39.823", -- [5]
							},
							["level"] = 11,
						}, -- [3]
					},
					["name"] = "Black Rook Hold",
					["zoneID"] = 1501,
					["objectives"] = {
						"Amalgam of Souls", -- [1]
						"Illysanna Ravencrest", -- [2]
						"Smashspite the Hateful", -- [3]
						"Lord Kur'talos Ravencrest", -- [4]
						"Enemy Forces", -- [5]
					},
				},
			},
		},
	},
}
